/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Category {
  'id' : string,
  'name' : string,
  'subcategories' : Array<string>,
}
export interface CategoryInput {
  'name' : string,
  'subcategories' : Array<string>,
}
export interface Item {
  'id' : string,
  'subcategory' : string,
  'name' : string,
  'description' : string,
  'available' : boolean,
  'imageUrl' : string,
  'category' : string,
  'price' : number,
}
export interface ItemInput {
  'subcategory' : string,
  'name' : string,
  'description' : string,
  'available' : boolean,
  'imageUrl' : string,
  'category' : string,
  'price' : number,
}
export type LoginResult = { 'ok' : string } |
  { 'err' : string };
export interface Order {
  'id' : string,
  'status' : string,
  'itemId' : string,
  'userName' : string,
  'paymentMethod' : string,
  'customDescription' : string,
  'deliveryDate' : bigint,
  'orderDate' : bigint,
  'deliveryType' : string,
  'address' : string,
  'itemName' : string,
  'phone' : string,
  'isCustomRequest' : boolean,
}
export interface OrderInput {
  'itemId' : string,
  'userName' : string,
  'paymentMethod' : string,
  'customDescription' : string,
  'deliveryDate' : bigint,
  'deliveryType' : string,
  'address' : string,
  'itemName' : string,
  'phone' : string,
  'isCustomRequest' : boolean,
}
export interface _SERVICE {
  'addCategory' : ActorMethod<[CategoryInput], Category>,
  'addItem' : ActorMethod<[ItemInput], Item>,
  'adminLogin' : ActorMethod<[string, string], LoginResult>,
  'createCustomRequest' : ActorMethod<[OrderInput], Order>,
  'createOrder' : ActorMethod<[OrderInput], Order>,
  'deleteCategory' : ActorMethod<[string], boolean>,
  'deleteItem' : ActorMethod<[string], boolean>,
  'getAllItems' : ActorMethod<[], Array<Item>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getCategories' : ActorMethod<[], Array<Category>>,
  'getItem' : ActorMethod<[string], [] | [Item]>,
  'getItems' : ActorMethod<[], Array<Item>>,
  'getItemsByCategory' : ActorMethod<[string], Array<Item>>,
  'toggleItemAvailability' : ActorMethod<[string], [] | [Item]>,
  'updateCategory' : ActorMethod<[string, CategoryInput], [] | [Category]>,
  'updateItem' : ActorMethod<[string, ItemInput], [] | [Item]>,
  'updateOrderStatus' : ActorMethod<[string, string], [] | [Order]>,
  'validateAdminToken' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];