/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CategoryInput = IDL.Record({
  'name' : IDL.Text,
  'subcategories' : IDL.Vec(IDL.Text),
});
export const Category = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'subcategories' : IDL.Vec(IDL.Text),
});
export const ItemInput = IDL.Record({
  'subcategory' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Float64,
});
export const Item = IDL.Record({
  'id' : IDL.Text,
  'subcategory' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Float64,
});
export const LoginResult = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
export const OrderInput = IDL.Record({
  'itemId' : IDL.Text,
  'userName' : IDL.Text,
  'paymentMethod' : IDL.Text,
  'customDescription' : IDL.Text,
  'deliveryDate' : IDL.Int,
  'deliveryType' : IDL.Text,
  'address' : IDL.Text,
  'itemName' : IDL.Text,
  'phone' : IDL.Text,
  'isCustomRequest' : IDL.Bool,
});
export const Order = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'itemId' : IDL.Text,
  'userName' : IDL.Text,
  'paymentMethod' : IDL.Text,
  'customDescription' : IDL.Text,
  'deliveryDate' : IDL.Int,
  'orderDate' : IDL.Int,
  'deliveryType' : IDL.Text,
  'address' : IDL.Text,
  'itemName' : IDL.Text,
  'phone' : IDL.Text,
  'isCustomRequest' : IDL.Bool,
});

export const idlService = IDL.Service({
  'addCategory' : IDL.Func([CategoryInput], [Category], []),
  'addItem' : IDL.Func([ItemInput], [Item], []),
  'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [LoginResult], []),
  'createCustomRequest' : IDL.Func([OrderInput], [Order], []),
  'createOrder' : IDL.Func([OrderInput], [Order], []),
  'deleteCategory' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteItem' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getAllItems' : IDL.Func([], [IDL.Vec(Item)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getItem' : IDL.Func([IDL.Text], [IDL.Opt(Item)], ['query']),
  'getItems' : IDL.Func([], [IDL.Vec(Item)], ['query']),
  'getItemsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Item)], ['query']),
  'toggleItemAvailability' : IDL.Func([IDL.Text], [IDL.Opt(Item)], []),
  'updateCategory' : IDL.Func(
      [IDL.Text, CategoryInput],
      [IDL.Opt(Category)],
      [],
    ),
  'updateItem' : IDL.Func([IDL.Text, ItemInput], [IDL.Opt(Item)], []),
  'updateOrderStatus' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(Order)], []),
  'validateAdminToken' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CategoryInput = IDL.Record({
    'name' : IDL.Text,
    'subcategories' : IDL.Vec(IDL.Text),
  });
  const Category = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'subcategories' : IDL.Vec(IDL.Text),
  });
  const ItemInput = IDL.Record({
    'subcategory' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Float64,
  });
  const Item = IDL.Record({
    'id' : IDL.Text,
    'subcategory' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Float64,
  });
  const LoginResult = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  const OrderInput = IDL.Record({
    'itemId' : IDL.Text,
    'userName' : IDL.Text,
    'paymentMethod' : IDL.Text,
    'customDescription' : IDL.Text,
    'deliveryDate' : IDL.Int,
    'deliveryType' : IDL.Text,
    'address' : IDL.Text,
    'itemName' : IDL.Text,
    'phone' : IDL.Text,
    'isCustomRequest' : IDL.Bool,
  });
  const Order = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'itemId' : IDL.Text,
    'userName' : IDL.Text,
    'paymentMethod' : IDL.Text,
    'customDescription' : IDL.Text,
    'deliveryDate' : IDL.Int,
    'orderDate' : IDL.Int,
    'deliveryType' : IDL.Text,
    'address' : IDL.Text,
    'itemName' : IDL.Text,
    'phone' : IDL.Text,
    'isCustomRequest' : IDL.Bool,
  });
  
  return IDL.Service({
    'addCategory' : IDL.Func([CategoryInput], [Category], []),
    'addItem' : IDL.Func([ItemInput], [Item], []),
    'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [LoginResult], []),
    'createCustomRequest' : IDL.Func([OrderInput], [Order], []),
    'createOrder' : IDL.Func([OrderInput], [Order], []),
    'deleteCategory' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteItem' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getAllItems' : IDL.Func([], [IDL.Vec(Item)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getItem' : IDL.Func([IDL.Text], [IDL.Opt(Item)], ['query']),
    'getItems' : IDL.Func([], [IDL.Vec(Item)], ['query']),
    'getItemsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Item)], ['query']),
    'toggleItemAvailability' : IDL.Func([IDL.Text], [IDL.Opt(Item)], []),
    'updateCategory' : IDL.Func(
        [IDL.Text, CategoryInput],
        [IDL.Opt(Category)],
        [],
      ),
    'updateItem' : IDL.Func([IDL.Text, ItemInput], [IDL.Opt(Item)], []),
    'updateOrderStatus' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(Order)], []),
    'validateAdminToken' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };